### ISSUE TITLE
Using full screen in Material UI components

### ISSUE THREAD

**Issue by haziqali-2019** [snakesilk/react-fullscreen#44] opened 2020-09-09 12:00 UTC
HI, I am using material ui. There seems to be some issue with material ui select options such that the options do not show on full screen maybe because the options are rendered outside the container element in the dom. I know this is something related to material ui and not this library but I was wondering if anyone faced this issue and was able to resolve it?

**Comment by pomle** [comment] 2020-09-17 09:57
@haziqali-2019 can you share your implementation?

**Comment by thalysonalexr** [comment] 2020-09-21 14:15
i have a same problem :(

**Comment by pomle** [comment] 2020-09-21 14:25
@thalysonalexr, please share your solution so someone can help you figure out why the problem exists.

**Comment by abayo-luc** [comment] 2020-10-10 16:57
To enable UI material popover/selector/menu in full screen, we have to append the popover to the full screen node, instead of being `document.body`.

Basically, change `container` prop to point to your full-screen component.

**Comment by pomle** [comment] 2020-10-20 12:11
@haziqali-2019, @thalysonalexr take a look at @abayo-luc. I think they got it. 

Had a similar problem with `overflow: hidden` and Material UI.

**Comment by Vasyl-Hnatyshyn** [comment] 2020-11-16 09:13
<Menu container={() => document.getElementById('fullscreen-node')}> ....</Menu>
Hi, I need to do the same but with the Select component and it doesn't support 'container'

**Comment by ferceballos** [comment] 2020-12-07 22:42
> `<Menu container={() => document.getElementById('fullscreen-node')}> ....</Menu>`
> It will append your popover inside your full screen node, instead of the default `document.body`

This seems to work just fine, but I have a bunch of these "popover" Material components in my project.

Is there any way to implement this change in all of the components at once instead of doing it one by one?

**Comment by pomle** [comment] 2020-12-09 07:53
@ferceballos, you probably have to update everywhere you use your menu but you could create your own Menu wrapper so you don't have to repeat this code. Not sure that is what you need.

```jsx
const MyMenu = ({children}) => {
  return (
    <Menu container={() => document.getElementById('fullscreen-node')}>
      {children}
    </Menu>
  );
}
```

**Comment by pomle** [comment] 2021-02-04 10:34
This seems to be a known issue with Material UI.
The issue is pinned.
Closing.

**Closed by pomle** 2021-02-04 10:34 UTC

**Comment by AntonOfTheWoods** [comment] 2021-12-27 12:52
If anyone else comes here looking for this, then `<Select MenuProps={{ container: ref?.current }} ... />` seems to be one way to achieve this.
